wujastyk/sushrutaproject

- docs/NAK 5-333 folio-text concordance.md
Made corrections in folio numbers. Put adhyAya numbers in vulgate column is still remain.
> Update NAK 5-333 folio-text concordance.md

- docs/KL 699 folio-text concordance.md
> Update KL 699 folio-text concordance.md

- docs/non-textual signs in MSS.md
Added syntax proposed by Charles [here](https://github.com/chchch/upama/issues/10#issuecomment-964546373)
> Minor update to "Update non-textual signs in MSS.md"

- docs/NAK 1-1079 folio-text concordance.md
> Update NAK 1-1079 folio-text concordance.md

- .gitignore
- 01-su.su/nak_1-1079_sutrasthana.txt
- 01-su.su/nak_5-333_sutrasthana.txt
- 06-su.ut/06-ut-vulgate-edition.txt
- 06-su.ut/kl_699_uttaratantra.txt
- 06-su.ut/nak_5-333_uttaratantra.txt
- 06-su.ut/provisional-edition_uttaratantra.txt
- docs/NAK 1-1079 folio-text concordance.md
- translation/translation 6-38.tex
- updates to the folio concordance of NAK 1-1079
- Added transcription of 1.14 in NAK 1-1079
- added several changes to 1.14 and 1.21 in 5-333 and KL 699
- updates to the edition and transcriptions of 6.38
- updates to the translation of 6.38
> Various updates

- 01-su.su/nak_1-1079_sutrasthana.txt
This pull request contains the transcript of 1.21 in 1-1079
> Transcriptions of NAK 1-1079

- 01-su.su/01-su-vulgate-edition.txt
- 01-su.su/nak_1-1079_sutrasthana.txt
- 06-su.ut/provisional-edition_uttaratantra.txt
added a transcript of SS.1.5 from NAK 1-1079
+ minor formatting changes in nak_1-1079_sutrasthana.txt made by Oxygen  
added minor improvements (typos etc.) to the vulgate
> SS.1.5 in NAK 1-1079  minor improvements to SS.1.5 in the vulgate

- 04-su.ci/04-ci-vulgate-edition.txt
> Added caesuras to 4.22

- 04-su.ci/04-ci-vulgate-edition.txt
Changed sequence of one pada at 4.25
> Added Caesuras to 4.32

- 05-su.ka/05-ka-vulgate-edition.txt
- 05-su.ka/kl_699_kalpasthana.txt
- 05-su.ka/nak_5-333_kalpasthana.txt
- 05-su.ka/provisional-edition_kalpasthana.txt
- translation/translation 5-02.tex
Modified translation of Ka 2.31-34 and corrected the transcriptions
> modified translation and corrected transcription

- 01-su.su/kl_699_sutrasthana.txt
- 01-su.su/nak_1-1079_sutrasthana.txt
- 01-su.su/nak_5-333_sutrasthana.txt
- 01-su.su/provisional-edition_sutrasthana.txt
> minor corrections1.6.1–7

- 01-su.su/kl_699_sutrasthana.txt
- 01-su.su/nak_1-1079_sutrasthana.txt
- 01-su.su/provisional-edition_sutrasthana.txt
Correcting wrong allocations in N, changes in SP.
> Changes in 1.6.19–20

- 01-su.su/nak_1-1079_sutrasthana.txt
- 01-su.su/provisional-edition_sutrasthana.txt
> two small changes SS 1.6

- 03-su.sa/03-za-vulgate-edition.txt
I also have split the line "bhavanti cAtra"
> Added caesuras to 3.7

- 01-su.su/01-su-vulgate-edition.txt
- 01-su.su/kl_699_sutrasthana.txt
- 01-su.su/nak_1-1079_sutrasthana.txt
- 01-su.su/nak_5-333_sutrasthana.txt
- 01-su.su/provisional-edition_sutrasthana.txt
I've also changed the header of 1.24 from [Cleaned-up text derived from MS N, waiting for Vitus's attention] to:
<head xml:lang="en">[Adhyāya 24]</head>
<p xml:lang="en">[Draft based on N (1.24.1–7) and K (1.24.7–12).]</p>
> Corrections in 1.24.11–12

- 01-su.su/01-su-vulgate-edition.txt
The lavaṇavarga ends at 1.46.330. I've added label 'iti lavaṇādivargaḥ' which was missing in transcription and also given in the vulgate edition. 1.46.331 to 339 is different text with no title.
> Added Caesuras to 1.46 (lavaṇavarga) 313-339

- 01-su.su/provisional-edition_sutrasthana.txt
- translation/translation 1-14.tex
Edited and added to translation 1.14.tex
Edited Ch.14 in sutra. prov. ed. file
> translation 1-14 and sutra prov.ed.

- 01-su.su/provisional-edition_sutrasthana.txt
- translation/translation 1-14.tex
Edited and added to translation 1-14.tex
Edited Ch. 14 of the provisional edition of Sutrasthana
> 1.14 and sutra. prov. ed.

- 06-su.ut-31-end/06-ut-vulgate-edition.txt
- 06-su.ut-31-end/kl_699_uttaratantra.txt
- 06-su.ut-31-end/nak_5-333_uttaratantra.txt
- 06-su.ut-31-end/provisional-edition_uttaratantra.txt
Prepared the first draft of 6.65 and made corrections to 6.65 of K and H. 
Replaced the iota macrons with i-macrons.
> updates in 6.65 and replacing ῑ with ī

- translation/chapters/translation 6-65.tex
Hello Prof. @wujastyk,
I am having trouble printing a longtable in chapter 65. The enumeration and definitions of the tantrayuktis in the SŚ closely resemble those of the Arthaśāstra. I thought it would be a nice idea to show the similarity with a table. I also have some questions regarding adding elements to the bib file. I'll ask you on Wednesday. 
Thanks,
Deepro
> added comparison with the Arthaśāstra

- 06-su.ut-31-end/06-ut-vulgate-edition.txt
- 06-su.ut-31-end/kl_699_uttaratantra.txt
- 06-su.ut-31-end/nak_5-333_uttaratantra.txt
- 06-su.ut-31-end/provisional-edition_uttaratantra.txt
- xml/06-su.ut/kl_699_uttaratantra.xml
Chapter 6.66 was added as a part of chapter 6.65 in H. I added it as the next chapter so that the text can be collated. Added some missing verses in K and added a provisional edition of 6.66. 
It will help me to look things up easily.
> Cleaning up 6.66

- 01-su.su-1-31/nak_5-333_sutrasthana-1-31.txt
just a deletion of an extra daṇḍa that I noticed while searching for an m in H.
> extra | minor correction in H

- 01-su.su-1-31/01-su-vulgate-edition-1-31.txt
- 01-su.su-1-31/kl_699_sutrasthana-1-31.txt
- 01-su.su-1-31/nak_1-1079_sutrasthana-1-31.txt
- 01-su.su-1-31/nak_5-333_sutrasthana-1-31.txt
- 01-su.su-1-31/provisional-edition_sutrasthana-1-31.txt
> update in 1.8

- 01-su.su-1-31/01-su-vulgate-edition-1-31.txt
- 01-su.su-1-31/kl_699_sutrasthana-1-31.txt
- 01-su.su-1-31/nak_1-1079_sutrasthana-1-31.txt
- 01-su.su-1-31/nak_5-333_sutrasthana-1-31.txt
- 01-su.su-1-31/provisional-edition_sutrasthana-1-31.txt
It should be ok now. I'll still check it once more after it is updated on Saktumiva.
> finalized 1.8

- 01-su.su-1-31/kl_699_sutrasthana-1-31.txt
- 01-su.su-1-31/nak_5-333_sutrasthana-1-31.txt
- 01-su.su-32-end/kl_699_sutrasthana-32-end.txt
Just noticed that the following parts are missing in H (Sūtrasthāna 1-31)
1. ff. 22v –29r
2. ff 52r line 4 – 52v line 4
3. ff. 61v line 6 – 63r line 5
4. Two hemistichs in f. 63r line 5
> facs and graphic links in K and H of Sū 1-31

- .github/workflows/txttoxml.yml
- .gitmodules
- xml/01-su.su/kl_699_sutrasthana.xml
- xml/02-su.ni/kl_699_nidanasthana.xml
- xml/04-su.ci/kl_699_cikitsasthana.xml
- xml/05-su.ka/kl_699_kalpasthana.xml
- xml/06-su.ut/kl_699_uttaratantra.xml
I had to do `git rm lib` and then redo the submodule with `git submodule add https://github.com/TST-Project/lib.git lib`, but it works now.
> updated libs

- translation/chapters/translation 2-01.tex
Changes in the translation of 2.1
> Update translation 2-01.tex

- 04-su.ci-1-20/kl_699_cikitsasthana_01-20.txt
- 04-su.ci-1-20/kl_699b_cikitsasthana_01-20.txt
- 04-su.ci-21-40/kl_699_cikitsasthana_21-40.txt
- 05-su.ka/kl_699_kalpasthana.txt
- 06-su.ut-01-30/kl_699_uttaratantra-1-30.txt
- 06-su.ut-01-30/nak_5-333_uttaratantra-1-30.txt
- 06-su.ut-31-44/kl_699_uttaratantra-31-44.txt
- 06-su.ut-45-66/06-ut-vulgate-edition-45-66.txt
- 06-su.ut-45-66/kl_699_uttaratantra-45-66.txt
- 06-su.ut-45-66/nak_5-333_uttaratantra-45-66.txt
The Jason file works well after changing the filenames. 
1. I added the remaining facs numbers. Now it should work fine. [Please check](https://wujastyk.github.io/sushrutaproject/xml/01-su.su/kl_699_sutrasthana.xml).  
2. Some parts of the manuscript K were not transcribed. I added some in 6.46 and 6.47. 
3. Also fixed the mismatched `xml:id`s of K and H in 6.47 (6.47.13-1 ... 6.47.13-5).  
4. It appears to me that an entire chapter 6.24 of the vulgate (6.51 of the Nepalese version) is not transcribed.
5. Some chapters in the Uttaratantra are not placed following the order they appear in the Nepalese version. They are arranged according to the order of the vulgate. I was not sure what we had finally decided about this problem. 
6. These are the issues that I noticed while working with the …
> added facs and some missing texts and some other corrections

- 06-su.ut-01-30/06-ut-vulgate-edition-1-30.txt
- 06-su.ut-01-30/nak_5-333_uttaratantra-1-30.txt
- 06-su.ut-45-66/kl_699_uttaratantra-45-66.txt
6.24 of the vulgate is 6.51 (Uttaratantra, Kāyacikitsā 16) of the Nepalese version. 
Added the missing chapter in K, where it is supposed to be. But since the chapter appears in the directory 06-su.ut.-01-30, it will not collate against the vulgate. 
In H, the chapter appears in the wrong position following the order of the vulgate.
The chapter needs to be added in the provisional edition file.
> added 6.24 of K and correction in H

- 01-su.su-1-31/01-su-vulgate-1938-1-31.txt
Verse no. 12 is left out in the vulgate(1931) and it's there in 1938 and it corresponds to verse no. 13 of vulgate(1931). Therefore, I followed the sequence of vulgate(1931) in made changes accordingly in 1938.
> XML IDs of Chapter 1-10 are compared with 1931 and did  some word breaks

- 01-su.su-1-31/01-su-vulgate-1931-1-31.txt
- 01-su.su-1-31/01-su-vulgate-1938-1-31.txt
- 01-su.su-1-31/bl_iolr_1842_sutrasthana.txt
- 01-su.su-1-31/nak_1-1079_sutrasthana-1-31.txt
- 01-su.su-1-31/provisional-edition_sutrasthana-1-31.txt
I'll add more changes after you merge what Harshal did.
> minor changes

- 01-su.su-32-end/01-su-vulgate-1938-32-end.txt
- 01-su.su-32-end/nak_1-1079_sutrasthana-32-end.txt
- 01-su.su-32-end/nak_5-333_sutrasthana-32-end.txt
> Changes in XML IDs of 1938, MS H, MS N correspond to 1938 edition. 
